version: '3'
services:
  web:
    build: .
    ports:
      - "80:80"
    volumes:
      - ./app:/app
    depends_on:
      - db
    environment:
      - REDIRECT_ADMIN_PASSWORD=phase-services
      - MONGO_INITDB_DATABSE=phase-services
      - MONGO_INITDB_ROOT_USERNAME=phase-services
      - MONGO_INITDB_ROOT_PASSWORD=phase-services
  db:
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABSE=phase-services
      - MONGO_INITDB_ROOT_USERNAME=phase-services
      - MONGO_INITDB_ROOT_PASSWORD=phase-services